# Generated by Django 5.1.3 on 2024-11-07 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('coordinatorId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('requestId', models.AutoField(primary_key=True, serialize=False)),
                ('requestDetails', models.TextField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsTrackingSystem',
            fields=[
                ('trackingId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('wheredelivery', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringAgency',
            fields=[
                ('monitoryagencyId', models.AutoField(primary_key=True, serialize=False)),
                ('contactInfo', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('recipientid', models.AutoField(primary_key=True, serialize=False)),
                ('organizationName', models.CharField(max_length=255)),
                ('contactinfo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contactInfo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HumanitarianAidSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('humanitarianCoordinatorId', models.IntegerField()),
                ('assignedRegion', models.CharField(max_length=255)),
                ('requestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.helprequest')),
            ],
        ),
    ]
