# Generated by Django 5.1.3 on 2025-01-06 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_humanitarianaidsystem_id_coordinator_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='coordinator_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.recipient'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='supplier_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humanitarianaidsystem',
            name='recipient',
            field=models.ForeignKey(default=500, on_delete=django.db.models.deletion.CASCADE, related_name='humanitarian_aid_systems', to='crm.recipient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
    ]
