# Generated by Django 5.1.3 on 2025-01-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_helprequest_coordinator_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringagency',
            name='contactInfo',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='contactinfo',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contactInfo',
        ),
    ]
