# Generated by Django 5.1.3 on 2025-01-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_monitoringagency_contactinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='role',
            field=models.CharField(choices=[('Analyst', 'Analyst'), ('Manager', 'Manager'), ('Advisor', 'Advisor'), ('Liaison', 'Liaison'), ('Consultant', 'Consultant'), ('Logistics', 'Logistics'), ('Director', 'Director'), ('Coordinator', 'Coordinator'), ('Assistant', 'Assistant'), ('Field Officer', 'Field Officer')], max_length=50),
        ),
    ]
