# Generated by Django 5.1.3 on 2025-01-06 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_coordinator_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='date_requested',
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.recipient'),
        ),
    ]
